- app/events/[id]/page.tsx
- app/events/newEvent/page.tsx
- app/events/page.tsx
** What: **
- Migrated the 'app/events' folder from the old repository into the new repository. This includes event IDs and the new event data structure.
- The migration covers the necessary data structure and functional code to manage event details, such as event date, location, required staff, and distance.
** Why: **
- This migration brings over the event functionality from the old repository, ensuring that the new project can properly handle and display events.
> chore(migration:events): move app/events folder 

- app/employees/[id]/page.tsx
- app/employees/newEmployee/page.tsx
- app/employees/page.tsx
- app/events/[id]/page.tsx
- app/events/newEvent/page.tsx
- app/events/page.tsx
- app/events/utils.ts
- app/requests/page.tsx
- app/schedule/page.tsx
- app/trucks/[id]/page.tsx
- app/trucks/page.tsx
- app/types.ts
This PR introduces two main improvements:
1. **Datetime Refactor**  
- Updated the UI to use a single `datetime` field instead of separate `date` and `time` fields  
- Added `extractDate` and `extractTime` utility functions for independently extracting and displaying date and time  
2. **Type Centralization & Deduplication**  
- Consolidated inline type declarations from individual page files into one file:  
- `app/types.ts`  
- Removed those redundant declarations from the page files  
---
- **refactor(datetime):**  
- Adapt components and display logic to the unified `datetime` model  
- Implement `extractDate` / `extractTime` utils  
- **chore(types):**  
- Created `app/types.ts` and moved all repeated type definitions into it  
- Cleaned up page files by removing their redundant type …
> refactor(datetime) & chore(types): adapt to unified datetime field and centralize type definitions

- public/events.json
** Description **
made all events current dates for testing
> chore: updated dated for events to be current 

- app/AlgApi/distance.ts
- app/about/page.tsx
- app/api/invite/route.ts
- app/components/AddressForm.tsx
- app/components/Footer.tsx
- app/components/Header.tsx
- app/contact/page.tsx
- app/employees/newEmployee/page.tsx
- app/events/[id]/page.tsx
- app/events/page.tsx
- app/globals.css
- app/page.tsx
- app/trucks/[id]/page.tsx
- app/tutorial/TutorialContext.tsx
- app/tutorial/components/TutorialOverlay.tsx
- app/types.ts
- public/events.json
Fix: Footer css
update: added tutorial steps for live demo
Update: added wage to create employee 
Fix: fix mismatch ui icons 
added about trucks page and contact page
> Fix: footer

- app/about/page.tsx
- app/api/invite/route.ts
- app/components/ClientLayoutContent.tsx
- app/components/Header.tsx
- app/components/QuickActions.tsx
- app/components/TutorialHighlight.tsx
- app/employees/[id]/page.tsx
- app/employees/newEmployee/page.tsx
- app/employees/page.tsx
- app/events/[id]/page.tsx
- app/events/page.tsx
- app/globals.css
- app/layout.tsx
- app/page.tsx
- app/schedule/components/Navigation.tsx
- app/schedule/components/ViewToggle.tsx
- app/schedule/page.tsx
- app/trucks/page.tsx
- app/tutorial/TutorialContext.tsx
- app/tutorial/components/TutorialOverlay.tsx
- public/events.json
Fix: removed wage and role from new employee creation
Fix: Dynamic header loading w/ hamburger menu
Fix: updated tutorial from dom targets to react state and added tutorial for create employee page
> fix: header and new employee page

- app/set-up-employee-info/page.tsx
- app/trucks/[id]/page.tsx
- app/trucks/add-trucks/page.tsx
- app/trucks/page.tsx
- database.types.ts
This PR implements a comprehensive truck management system with full Supabase integration, replacing JSON-based data storage.
**Truck Addition Page** (`/trucks/add-trucks`)
- AddressForm integration for address input and validation
- Truck type selection (Food Truck, Beverage Truck, Dessert Truck)
- Capacity options and packing list management
- Address validation with coordinate storage
**Enhanced Truck Listing Page** (`/trucks`)
- Supabase data fetching instead of JSON files
- Truck type filtering with filter buttons
- Add truck button for direct navigation
**Truck Edit Page** (`/trucks/[id]`)
- Full CRUD operations for truck properties
- Address management (update existing or create new)
- Form validation with error handling
- Event association display
- Database schema updates with …
> feat(trucks): Complete Supabase Integration for Truck Management System

- app/api/invite/route.ts
- app/set-password/page.tsx
verify user with session instead of token form param
> fix: invite user link to not expose user email

- app/employees/page.tsx
- app/events/[id]/components/EmployeeSelectionModal.tsx
- app/events/[id]/components/ServerAssignmentsSection.tsx
- app/events/[id]/components/TruckAssignmentsSection.tsx
- app/events/[id]/page.tsx
- app/events/newEvent/page.tsx
- app/events/page.tsx
- app/login/page.tsx
- app/page.tsx
- app/requests/page.tsx
- app/time-off-request/page.tsx
- app/tutorial/TutorialContext.tsx
- app/tutorial/components/TutorialOverlay.tsx
- app/types.ts
- database.types.ts
- lib/supabase/assignments.ts
- lib/supabase/events.ts
- lib/supabase/timeOffRequests.ts
Complete employee management system with full Supabase integration for assignments and time off requests.
- Auto-assign servers by distance and availability
- Real-time conflict checking (time off, other events, day availability)
- Automatic event status updates when fully assigned
- Employee request form with date validation
- Admin interface for request management (accept/reject/delete)
- Full Supabase integration for time off requests
- Prevents assignment conflicts with approved time off
- Multi-level availability checks in employee selection modal
- Visual indicators for unavailable employees
- Consistent validation across auto and manual assignment
- Real-time dashboard with Supabase data
- Unified assignment UI with responsive layout
- Interactive filtering and status management
> feat: Enhanced Employee Assignment System with Supabase Integration & Time Off Management

- app/employee-schedule/page.tsx
- app/my-time-off-requests/page.tsx
- app/schedule/components/Calendar.tsx
- app/schedule/components/EventContent.tsx
- lib/supabase/assignments.ts
- Employees can view their assigned events and truck assignments
- Daily, weekly, monthly calendar views
- Click events to view details
- Fetches data from Supabase
- View personal time-off requests
- Filter by status (All, Pending, Accepted, Rejected)
- Sort by newest
- Shows request details and duration
- Made `extendedProps` optional in Calendar component
- Added employee assignment queries to assignments API
> feat: Add Employee Schedule and Time-Off Request Management Pages

- app/components/Header.tsx
- app/employees/page.tsx
- app/events/page.tsx
What
- Highlighted the active nav link in the header (yellow text, bold, underline)
- Removed Add New Employee and Add New Event buttons
- Removed the "Event Management" header from the Events page
- Removed the "Employee Management" header from the Employees page
Why
- Improve user experience by clearly showing the current page
- Clean up the UI by removing unused or redundant elements
> Add page indicator to highlight current page

- app/components/Sidebar.tsx
- app/globals.css
> indented subpages on sidebar

- app/layout.tsx
changed favicon to company logo
> changed favicon to company logo

- app/components/AddressForm.tsx
- app/events/[id]/components/EditEventModal.tsx
- app/events/[id]/components/EmployeeSelectionModal.tsx
- app/events/[id]/components/ServerAssignmentsSection.tsx
- app/events/[id]/components/TruckAssignmentModal.tsx
- app/events/[id]/components/TruckAssignmentsSection.tsx
- app/events/[id]/page.tsx
- app/events/newEvent/page.tsx
- app/types.ts
- lib/supabase/assignments.ts
- lib/supabase/employeeAvailability.ts
- lib/supabase/employees.ts
- lib/supabase/trucks.ts
added end date to add event and server assignment 
added sorting to select employees (with cache and filters to limit db calls and load times)
added sorting to select trucks (with cache to limit db calls and driver availability checks)
added availability check for trucks on event creation (with driver availability checks)
added functionality to remove servers from event quickly added same function to trucks but ran into rls error 
made availability checks centralized function in supabase files 
auto capitalize employee names
> event creation fixes

- app/api/invite/route.ts
- app/components/AuthGuard.tsx
- app/forgotpassword/page.tsx
- app/set-password/page.tsx
in this pr:
- added new page for password recovery page
- change auth check: supabase automatically logs in user with the token sent with the link in email so use getUser() from supabase and checked verification
- added new page to public page in authgaurd so it can be access without login
> feat(auth): add password recovery

- app/api/resend-invite/route.ts
- app/components/Sidebar.tsx
- app/pending-employees/PendingEmployeesList.tsx
- app/pending-employees/ResendButton.tsx
- app/pending-employees/SearchInput.tsx
- app/pending-employees/page.tsx
- app/set-password/page.tsx
in this pr:
- added a page to display list of employees that did not accept invite with re-send invite button 
- added resend-invite route 
- added token validation for both hash token(#access_token=...) or #code...
- added redirect to pending employees page in sidebar
> feat(auth): re-send invite for expired user invites

- app/reports/employee-availability/page.tsx
- app/reports/page.tsx
- app/reports/payroll/page.tsx
- app/reports/payroll/stats.json
- app/reports/payroll/taxCalculations.json
- app/reports/time-off-requests/page.tsx
- app/reports/truck-availability/page.tsx
- lib/supabase/assignments.ts
- lib/supabase/events.ts
- package-lock.json
- package.json
made reports pages 
payroll calculates tax and stat holidays via date-holiday npm package 
(payroll doesnt account for truck assignments because tehjibs clock in clock out feature should set a shift for them and payroll should take into account shifts but I cannot test as i cannot create or edit shift times yet)
> feat: add report pages for employees/trucks/timeOffRequest

- app/my-time-off-requests/page.tsx
- app/requests/page.tsx
- app/time-off-request/page.tsx
fixed time discrepancy error in time off request saving as diff time
> fix time off request time saving as incorrect time (centeralized date formatting)

- app/employee-schedule/page.tsx
- app/schedule/components/Calendar.tsx
Summary
This PR addresses several issues and improvements related to the calendar integration in the employee schedule view:
The employee schedule page now renders without type or lint errors.
Calendar events display correctly for daily, weekly, and monthly views.
The build and linter pass without errors.
Related Issues
Fixes type errors for calendar events.
Resolves Prettier and ESLint warnings.
Please review and let me know if any further changes are needed!
> calender-ui

- app/events/[id]/components/EmployeeSelectionModal.tsx
- app/globals.css
- app/schedule/new/EmployeeSelectionModalForAssignment.tsx
- app/schedule/new/page.tsx
added page to add shift assignments connects to assingments table and event id required
> Feature: shift-page

- app/components/ErrorModal.tsx
- app/globals.css
- app/pending-employees/PendingEmployeesList.tsx
update error modal to match new ui 
sorted pending employees
> chore: update ui for error modal

- app/admin-checkin-logs/components/EventLogCard.tsx
- app/admin-checkin-logs/components/LogListItem.tsx
- app/admin-checkin-logs/components/LogListSection.tsx
- app/admin-checkin-logs/page.tsx
- app/check-in/page.tsx
- app/check-in/utils.ts
- lib/supabase/checkin.ts
fix time zone error in check in feature by using same logic as time zone handling in event feature
> fix(check-in): time zone error 

- app/about/page.tsx
- app/api/events/assigned/route.ts
- app/check-in/components/MainAssignmentCard.tsx
- app/check-in/components/ScheduleList.tsx
- app/check-in/page.tsx
- app/components/Header.tsx
- app/components/Sidebar.tsx
- app/components/SidebarSection.tsx
- app/employees/[id]/page.tsx
- app/employees/page.tsx
- app/events/[id]/components/ServerAssignmentsSection.tsx
- app/events/[id]/components/TruckAssignmentsSection.tsx
- app/events/[id]/page.tsx
- app/events/page.tsx
- app/page.tsx
- app/schedule/components/Calendar.tsx
- app/schedule/page.tsx
- app/trucks/page.tsx
- app/types.ts
- lib/supabase/assignments.ts
- lib/supabase/employees.ts
- lib/supabase/events.ts
added is admin checks and redirects to entire app 
side bar loads employee safe routes only 
events only load by employee id 
schedule only loads by employee id 
profile button to edit their own profile
packing list loads only assigned trucks for next 2 weeks giving servers less access
trucks button is now contact page 
reports is blocked 
employees and events route to new limited view table in db
> Employee view

- app/components/Header.tsx
- app/components/ProfileAvatar.tsx
- app/components/ProfileDropdown.tsx
- app/globals.css
- database.types.ts
in this pr:
- align header icons with sidebar content
- add note field to event table, truck_id field in assignment table and update generated types
- change profile button in header styling
- add mobile-specific profile dropdown with My Profile and Logout options
> feat(ui): visual updates to profile and update types for schema

- app/globals.css
- app/login/page.tsx
Fixed login page UI and made it work on mobile.
- Login page now works on mobile
- Fixed the layout and styling
> feat: make login page mobile responsive and fix design

- .github/workflows/validate-pr.yml
- app/api/geocode/autocomplete/route.ts
- app/components/AddressForm.tsx
- app/employees/[id]/page.tsx
- app/employees/page.tsx
- app/events/[id]/components/EditEventModal.tsx
- app/events/[id]/page.tsx
- app/events/newEvent/page.tsx
- app/events/page.tsx
- app/types.ts
- lib/utils.ts
**Autocomplete Address Feature**: Integrated Geoapify API for real-time address suggestions with Alberta-only filtering, optimized with debouncing, caching, and rate limiting for improved performance. The autocomplete is seamlessly integrated into the street number input field with automatic postal code cleaning (removes province prefixes).
**Performance Optimizations**: Implemented 300ms debouncing, 5-minute in-memory caching, reduced API timeouts (5s), and rate limiting (500ms) to minimize API calls and enhance user experience.
**Address save in event pages**: Fixed address data saving and validation in event creation and editing pages by removing duplicate location field and using individual address fields 
**Postal code display**: Ensured postal code field only contains postal code …
> feat: add auto-complete address feature
